/* users*/
ALTER TABLE users
ALTER COLUMN created_date TYPE TIMESTAMP USING NULLIF(created_date, 'NULL')::TIMESTAMP,
ALTER COLUMN last_login TYPE TIMESTAMP USING NULLIF(last_login, 'NULL')::TIMESTAMP,
ALTER COLUMN active TYPE boolean USING NULLIF(active, 'NULL')::boolean;

/* Receipts */
ALTER TABLE receipts
ALTER COLUMN create_date TYPE TIMESTAMP USING NULLIF(create_date, 'NULL')::TIMESTAMP,
ALTER COLUMN date_scanned TYPE TIMESTAMP USING NULLIF(date_scanned, 'NULL')::TIMESTAMP,
ALTER COLUMN FINISHED_DATE TYPE TIMESTAMP USING NULLIF(FINISHED_DATE, 'NULL')::TIMESTAMP,
ALTER COLUMN PURCHASE_DATE TYPE TIMESTAMP USING NULLIF(PURCHASE_DATE, 'NULL')::TIMESTAMP,
ALTER COLUMN POINTS_AWARDED_DATE TYPE TIMESTAMP USING NULLIF(POINTS_AWARDED_DATE, 'NULL')::TIMESTAMP;

/*brands*/
ALTER TABLE brands
ALTER COLUMN top_brand TYPE bool USING NULLIF(top_brand, 'NULL')::bool;

/*foreign key*/
ALTER TABLE receipts
ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id)
REFERENCES users(user_id);











